apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp
    version: 2.6.1
spec:
  type: NodePort
  selector:
    app: myjavaapp
    version: 2.6.1
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
